sudo: false
language: node_js
node_js:
  - '5.11'

cache:
  directories:
    - node_modules

before_script:
  - npm prune

after_success:
  - npm run coverage
  - npm run semantic-release

branches:
  except:
  - /^v\d+\.\d+\.\d+$/

notifications:
  slack:
    secure: dZiRYM7H6b+DesOS2y0BwTmBYIzXSDF5rV58fG4waYEEjPxD+BYMXMzliRBXe6Xw/H/ravBztY07JRbOG3Wi19GnUYllartdw+kdIgQQ33cKUl+m61aNclAHzfiF8waFNXy1n6u98v5ObY+IvPAV2/mVbd/VoG/WkW+TVVjHiaDzkcOlzY6U85ZJDZ29z7T+ZVbqOhfR4NSvI8Gs1q/I1I50sHcq128gT/wgYEWanCoJpWi7cdUoZDiGr0rAJeCsbujLLqp1QwRBJZUAIe/8A/M3c13U2efAA6XeR3GPJ4SPcoiZtR2xFC4WPOLzsIH5SOO8PC5I8of3P+YaGy2iGEStR15hKXHqRLtCHXgVavs4tvYLOtqxf0f7/Uz7PVJf0oHHjiZ55McL/Y77plhCU8i9WxMJgk6ZOktK0KATq5jEapIFfy0UmDcawAF9XvZp8o9tAxKx9/WRLkviM/l4BTWbV5YufqGF8gKCYLakZtYOxWHMDMLfS6UuYZEm0Fga+Z97DAuq4Koh0RPtojzrqHAzMC5g3NeVxrM/MmYWwaxEFVJiEt+W3AGFhzEMBwofizsXP0b6tscslb0qaD0Z1b0LyDM0mIMBx0QxaPQt7vqbc9ZkbStRY3od5qYqruel48wkJa9oFvD6BMkUZGuzFKnigQPQq7XdFCyGg8lJg+Q=
